
services:
  db:
    image: mysql:8.0
    container_name: emsi_mysql
    environment:
      MYSQL_DATABASE: evoleo
      MYSQL_USER: emsi_user
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - emsi-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 5s
      retries: 10

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: emsi_backend
    ports:
      - "8000:8000"
    restart: unless-stopped
    environment:
      - MYSQL_HOST=db
      - MYSQL_USER=emsi_user
      - MYSQL_PASSWORD=root
      - MYSQL_DATABASE=evoleo
      - DATABASE_URL=mysql+pymysql://emsi_user:root@db:3306/evoleo
      - SECRET_KEY=your-secret-key-here
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY:-sk_test_default}
      - STRIPE_WEBHOOK_SECRET=${STRIPE_WEBHOOK_SECRET:-whsec_default}
      - PYTHONPATH=/app
    volumes:
      - ./backend:/app/backend
      - ./backend/.env:/app/backend/.env
    command: sh -c "uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - emsi-network

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: emsi_frontend
    ports:
      - "3000:80"
    restart: unless-stopped
    environment:
      REACT_APP_API_URL: /api
    depends_on:
      - backend
    networks:
      - emsi-network

  nginx:
    image: nginx:alpine
    container_name: emsi_nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./front_end/build:/usr/share/nginx/html
    depends_on:
      - frontend
      - backend
    restart: unless-stopped
    networks:
      - emsi-network

networks:
  emsi-network:
    driver: bridge

volumes:
  mysql_data:
